= Követelmény specifikáció

[cols="5,3,2"]
|===
| Követelmény | Használati esetek | Állapot

| *Állatok kezelése*

  A rendszerben lévő állatok listázása.
  Új állat rögzítése a rendszerben.
  Kiválasztott állat metaadatainak megtekintése, azok módosítása
  Külön használati eset kell a név vagy a súly változtatására.
  Az eladott állatok törölhetőek legyenek a rendszerből
| Állatok CRUD + listázó + átnevezés + súlyváltozás
| Backend elkészítve

| *Állateledelek kezelése*

A rendszerben lévő állateledelek listázása.
Új állateledel rögzítése a rendszerben.
Kiválasztott állateledel metaadatainak megtekintése
Állateledel törlése
|
* Állateledelek listázása

* Állateledel létrehozása

* Állateledel megtekintése

* Állateledel törlése
| Backend elkészítve

| *Etetések*

Kerüljenek rögzítésre az állatok etetései.
A korábbi etetések listázása.
Egy kiválasztott állat számára adott étel átlagos súlyaának megtekintése.
Átlagos állatedelek súlya az etetések során állatonként is.
Az állat súlyváltozása alapján szükség esetén új adag mennyiség javaslata.

|
* Etetések listázása.

* Egy állat átlagos étel fogyasztásának megtekinése.

* Az állatok átlagos ételfogyasztásának listázása.

* Javaslat új adag mennyiségre a kiválasztott állat számra.
| Backend elkészítve

| *Súlyváltozások*

Minden mérlegelés eredménye tárolásra kerül a rendszerben.

Egy kiválasztott állat súlyváltozásainak megtekintése
|
 * Állat új, mért súlyának rögzítése
 * Állat súlyváltozásainak megtekintése
| Backend elkészítve

| A rendszerbe csak felhasználónévvel és jelszóval lehet bejeletnkezni.
Két szintű szerepkör van: Általános felhasználó és Adminisztrátor
A törléseket csak adminisztrátor szerepkörrel engedjük.
| Bejelentkezés, Kijelentkezés
| Elkészítésre vár

|===

link:README.adoc[Vissza]