GET http://localhost:8080/words/query
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJPbMOhaCAyZXMgR29sZmd1c3p0w6F2Iiwicm9sZXMiOltdLCJpYXQiOjE3NDI5OTMyMzcsImV4cCI6MTc0Mjk5NjgzN30.DI0bC3r7jjh5ogRe2Wv0RlyuciZu1Ns50leTJlxvGjlMiHbw5xYjM31ldHXJglOtQ5bp4xfsp9pr-iop0sgt8g